Repository scarletYewon/Contacts, pull requests merged in 2023-09, with the labels that each got.

#1 viewPager, tabLayout 적용
  app/.idea/compiler.xml
  app/.idea/gradle.xml
  app/.idea/kotlinc.xml
  app/.idea/misc.xml
  app/app/build.gradle
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/java/com/test/mycontacts/ViewPagerAdapter.kt
  app/app/src/main/res/drawable/icon_plus.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/values/themes.xml
Labels: feature

#2 [UI] Mypage fragment
  app/.idea/kotlinc.xml
  app/app/build.gradle
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/java/com/test/mycontacts/MyPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/fragmentActivity.kt
  app/app/src/main/res/drawable/gradient_background.xml
  app/app/src/main/res/drawable/hyein.png
  app/app/src/main/res/drawable/hyoree.jpg
  app/app/src/main/res/drawable/ic_floatingbutton.png
  app/app/src/main/res/drawable/rounded_button.xml
  app/app/src/main/res/drawable/rounded_button2.xml
  app/app/src/main/res/layout/activity_fragment.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/fragment_my_page.xml
  app/app/src/main/res/values/strings.xml
  app/build.gradle
Labels: UI

#3 [Fix] viewPager Act + MyPage Frag
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/ViewPagerAdapter.kt
  app/app/src/main/java/com/test/mycontacts/fragmentActivity.kt
  app/app/src/main/res/layout/activity_fragment.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/fragment_my_page.xml
Labels: Fix

#5 [Feature]ContactListRecycler
  .idea/Contacts.iml
  .idea/modules.xml
  .idea/vcs.xml
  app/.idea/misc.xml
  app/app/build.gradle
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/DuduMainActivity.kt
  app/app/src/main/java/com/test/mycontacts/ItemAdapter.kt
  app/app/src/main/java/com/test/mycontacts/JypFragment.kt
  app/app/src/main/java/com/test/mycontacts/MyItems.kt
  app/app/src/main/java/com/test/mycontacts/SmFragment.kt
  app/app/src/main/res/drawable/img_like.png
  app/app/src/main/res/drawable/img_like2.png
  app/app/src/main/res/drawable/jyp_bae.png
  app/app/src/main/res/drawable/jyp_haewon.png
  app/app/src/main/res/drawable/jyp_jiwoo.png
  app/app/src/main/res/drawable/jyp_kyujin.png
  app/app/src/main/res/drawable/jyp_lily.png
  app/app/src/main/res/drawable/jyp_sullyoon.png
  app/app/src/main/res/drawable/sm_hyoyeon.png
  app/app/src/main/res/drawable/sm_seohyun.png
  app/app/src/main/res/drawable/sm_sooyoung.png
  app/app/src/main/res/drawable/sm_sunny.png
  app/app/src/main/res/drawable/sm_taeyeon.png
  app/app/src/main/res/drawable/sm_tiffany.png
  app/app/src/main/res/drawable/sm_yoona.png
  app/app/src/main/res/drawable/sm_yuri.png
  app/app/src/main/res/layout/activity_dudu_main.xml
  app/app/src/main/res/layout/fragment_jyp.xml
  app/app/src/main/res/layout/fragment_sm.xml
  app/app/src/main/res/layout/item_recyclerview.xml
Labels: UI, feature

#6 [Fix] Activity -> Fragment
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/DuDu.kt
  app/app/src/main/res/layout/fragment_dudu.xml
Labels: Fix

#8 [Feature] AddDialog
  app/app/src/main/java/com/test/mycontacts/AddDialog.kt
  app/app/src/main/java/com/test/mycontacts/ContactList.kt
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/res/drawable/basic.png
  app/app/src/main/res/layout/dialog.xml
  app/app/src/main/res/layout/fragment_dudu.xml
Labels: feature, Fix

#11 Feature/mypage2
  app/app/build.gradle
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/AddDialog.kt
  app/app/src/main/java/com/test/mycontacts/AlarmReceiver.kt
  app/app/src/main/java/com/test/mycontacts/ContactList.kt
  app/app/src/main/java/com/test/mycontacts/DetailPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/ItemAdapter.kt
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/java/com/test/mycontacts/MyItems.kt
  app/app/src/main/java/com/test/mycontacts/MyPageFragment.kt
  app/app/src/main/res/drawable/ic_aaaa_bbbb.png
  app/app/src/main/res/drawable/img_like3.xml
  app/app/src/main/res/drawable/img_like4.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/dialog.xml
  app/app/src/main/res/layout/fragment_detail_page.xml
  app/app/src/main/res/layout/fragment_dudu.xml
  app/app/src/main/res/layout/fragment_sm.xml
  app/app/src/main/res/layout/item_recyclerview.xml
Labels: Design

#15 [UI] Splash
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/test/mycontacts/SplashActivity.kt
  app/app/src/main/res/anim/bounce.xml
  app/app/src/main/res/anim/linear.xml
  app/app/src/main/res/drawable/mess.png
  app/app/src/main/res/layout/anim_splash.xml
  app/app/src/main/res/values/colors.xml
  app/app/src/main/res/values/themes.xml
Labels: UI

#18 [FEAT] 연락처 리스트에 사진 추가하는거 구현
  app/app/src/main/java/com/test/mycontacts/AddDialog.kt
  app/app/src/main/java/com/test/mycontacts/AlarmReceiver.kt
  app/app/src/main/java/com/test/mycontacts/ContactList.kt
  app/app/src/main/java/com/test/mycontacts/DetailPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/ItemAdapter.kt
  app/app/src/main/java/com/test/mycontacts/JypFragment.kt
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/java/com/test/mycontacts/MyItems.kt
  app/app/src/main/java/com/test/mycontacts/MyPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/SmFragment.kt
  app/app/src/main/java/com/test/mycontacts/test.kt
  app/app/src/main/res/drawable/img_like.png
  app/app/src/main/res/drawable/img_like2.png
  app/app/src/main/res/drawable/img_like4.xml
  app/app/src/main/res/layout/dialog.xml
  app/app/src/main/res/layout/fragment_detail_page.xml
  app/app/src/main/res/layout/fragment_jyp.xml
  app/app/src/main/res/layout/fragment_my_page.xml
  app/app/src/main/res/layout/fragment_recyclerview.xml
  app/app/src/main/res/layout/fragment_sm.xml
  app/app/src/main/res/layout/item_recyclerview.xml
  app/app/src/main/res/layout/item_recyclerview2.xml
  app/app/src/main/res/layout/test_activity.xml
Labels: feature

#20 [Merge] main <- dev
  app/app/src/main/java/com/test/mycontacts/AddDialog.kt
  app/app/src/main/java/com/test/mycontacts/AlarmReceiver.kt
  app/app/src/main/java/com/test/mycontacts/ContactList.kt
  app/app/src/main/java/com/test/mycontacts/DetailPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/ItemAdapter.kt
  app/app/src/main/java/com/test/mycontacts/JypFragment.kt
  app/app/src/main/java/com/test/mycontacts/MainActivity.kt
  app/app/src/main/java/com/test/mycontacts/MyItems.kt
  app/app/src/main/java/com/test/mycontacts/MyPageFragment.kt
  app/app/src/main/java/com/test/mycontacts/SmFragment.kt
  app/app/src/main/java/com/test/mycontacts/test.kt
  app/app/src/main/res/drawable/img_like.png
  app/app/src/main/res/drawable/img_like2.png
  app/app/src/main/res/drawable/img_like4.xml
  app/app/src/main/res/drawable/rectangle.xml
  app/app/src/main/res/font/archivolight.ttf
  app/app/src/main/res/layout/dialog.xml
  app/app/src/main/res/layout/fragment_detail_page.xml
  app/app/src/main/res/layout/fragment_jyp.xml
  app/app/src/main/res/layout/fragment_my_page.xml
  app/app/src/main/res/layout/fragment_recyclerview.xml
  app/app/src/main/res/layout/fragment_sm.xml
  app/app/src/main/res/layout/item_recyclerview.xml
  app/app/src/main/res/layout/item_recyclerview2.xml
  app/app/src/main/res/layout/test_activity.xml
Labels: merge

#21 [BUG_FIX] : 🐛알림시간 0으로 체크해도 알림 오는거 수정
  app/app/src/main/java/com/test/mycontacts/AddDialog.kt
Labels: bug
